language: ruby
bundler_args: --without development production staging
sudo: false
rvm:
  - 2.2.2
addons:
  postgresql: 9.3
  code_climate:
    repo_token: 18150ec1de29b6278ac619e038b49a2e12ad556813b4827950c9737cbb9776e0
before_script:
  - psql -c 'create database unep_wcmc_test' -U postgres
  - cp config/database.yml.example config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate
notifications:
  slack: wcmc:g3eTH5tO8AusrAVOxP5gDEMM
