language: ruby
bundler_args: --without development production staging
rvm:
  - 2.2.2
addons:
  postgresql: 9.3
before_script:
  - psql -c 'create database unep_wcmc_test' -U postgres
  - cp config/database.yml.example config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate
notifications:
  slack: wcmc:g3eTH5tO8AusrAVOxP5gDEMM
