production_dashboard_urls: &production_dashboard_urls
  speciesplus_dashboard_url: 'https://www.speciesplus.net/api/v1/dashboard_stats/:country'
  protectedplanet_dashboard_url: 'https://www.protectedplanet.net/api2/countries/' # TODO
  carbon_dashboard_url: 'https://carbon-tool.cartodb.com/api/v2/sql'

default_dashboard_urls: &default_dashboard_urls
  speciesplus_dashboard_url: 'https://sapi.sapi-staging.linode.unep-wcmc.org/api/v1/dashboard_stats/:country'
  protectedplanet_dashboard_url: 'https://www.protectedplanet.net/api2/countries/' #TODO
  carbon_dashboard_url: 'https://carbon-tool.cartodb.com/api/v2/sql'

development:
  secret_key_base: '4ab6dc786dc1904ea29b04aee5c6f25d4fbfdc9672ea569dde62b92a4fbfe2a2f698818004cfb31c83420b35a11c150c1601498cd630f387f38c3b970616d742'
  max_mind:
    country_db : '/usr/share/GeoIP/GeoIP.dat'
  capistrano_slack: ''
  <<: *default_dashboard_urls

test:
  secret_key_base: '4ab6dc786dc1904ea29b04aee5c6f25d4fbfdc9672ea569dde62b92a4fbfe2a2f698818004cfb31c83420b35a11c150c1601498cd630f387f38c3b970616d742'
  max_mind:
    country_db : '/usr/share/GeoIP/GeoIP.dat'
  capistrano_slack: ''
  <<: *default_dashboard_urls

staging_and_production: &defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  mailer:
    address: <%= ENV["MAILER_ADDRESS_KEY"] || "" %>
    port: <%= ENV["MAILER_PORT_KEY"] || "" %>
    domain: <%= ENV["MAILER_DOMAIN_KEY"] || "" %>
    username: <%= ENV["MAILER_USERNAME_KEY"] || "" %>
    password: <%= ENV["MAILER_PASSWORD_KEY"] || "" %>
    asset_host: <%= ENV["MAILER_ASSET_HOST_KEY"] || "" %>
    host: <%= ENV["MAILER_HOST_KEY"] || "" %>

  max_mind:
    country_db : <%= ENV["MAX_MIND_COUNTRY_DB"] || "" %>

production:
  <<: *defaults
  <<: *production_dashboard_urls

staging:
  <<: *defaults
  <<: *default_dashboard_urls
