development:
  secret_key_base: '4ab6dc786dc1904ea29b04aee5c6f25d4fbfdc9672ea569dde62b92a4fbfe2a2f698818004cfb31c83420b35a11c150c1601498cd630f387f38c3b970616d742'
  max_mind:
    country_db : '/usr/share/GeoIP/GeoIP.dat'
  capistrano_slack: ''

test:
  secret_key_base: '4ab6dc786dc1904ea29b04aee5c6f25d4fbfdc9672ea569dde62b92a4fbfe2a2f698818004cfb31c83420b35a11c150c1601498cd630f387f38c3b970616d742'
  max_mind:
    country_db : '/usr/share/GeoIP/GeoIP.dat'
  capistrano_slack: ''

staging_and_production: &defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  exception_notification_email: <%= ENV["EXCEPTION_NOTIFICATION_EMAIL"] %>
  exception_notification_slack_webhook: <%= ENV["EXCEPTION_NOTIFICATION_SLACK_WEBHOOK"] %>

  mailer:
    address: <%= ENV["MAILER_ADDRESS_KEY"] || "" %>
    port: <%= ENV["MAILER_PORT_KEY"] || "" %>
    domain: <%= ENV["MAILER_DOMAIN_KEY"] || "" %>
    username: <%= ENV["MAILER_USERNAME_KEY"] || "" %>
    password: <%= ENV["MAILER_PASSWORD_KEY"] || "" %>
    asset_host: <%= ENV["MAILER_ASSET_HOST_KEY"] || "" %>
    host: <%= ENV["MAILER_HOST_KEY"] || "" %>

  max_mind:
    country_db : <%= ENV["MAX_MIND_COUNTRY_DB"] || "" %>

production:
  <<: *defaults

staging:
  <<: *defaults
